baseURL = 'https://davidwardan.github.io/davidwardan.github.io/'
languageCode = 'en-us'
title = "David's Blog"
theme = 'PaperMod'
relativeURLs = true

[params]
  defaultTheme = "auto"

[caches]
  [caches.images]
    dir = ':cacheDir/images'