baseURL = 'https://davidwardan.github.io/davidwardan.github.io/'
languageCode = 'en-us'
title = "David's Blog"
theme = 'PaperMod'
relativeURLs = true

[params]
  defaultTheme = "auto"

  [params.profileMode]
    enabled = true
    title = "David Wardan"
    subtitle = "Machine Learning Engineer | PhD Student"
    imageUrl = "images/profile.png"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "David Wardan"
    buttons = [
      { name = "Posts", url = "/posts" }
    ]

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/davidwardan"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/david-wardan/"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/davidwardan"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:wardandavid@gmail.com"

[caches]
  [caches.images]
    dir = ':cacheDir/images'