baseURL = 'https://davidwardan.github.io/davidwardan.github.io/'
languageCode = 'en-us'
title = "David's Blog"
theme = 'PaperMod'
relativeURLs = true

[params]
  defaultTheme = "auto"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  defaultTheme = "auto"
  profileMode = 
    { enabled = true, title = "David Wardan", 
    subtitle = "Machine Learning Engineer | PhD Student", 
    imageUrl = "images/profile.png", 
    imageWidth = 120, 
    mageHeight = 120, 
    imageTitle = "David Wardan", 
    buttons = [{name = "Posts", url = "/posts"}]}

[params.socialIcons]
  - name = "github"
    url = "https://github.com/davidwardan"
  - name = "linkedin"
    url = "https://linkedin.com/in/davidwardan"
  - name = "twitter"
    url = "https://twitter.com/davidwardan"
  - name = "email"
    url = "mailto:wardandavid@gmail.com"